Enhance dev-workspace scripts with improved error handling and user guidance. Added help message for usage instructions, checks for the existence of the .env file, and refactored the run script to streamline environment initialization. Updated stop script to include .env file validation.

diff --git a/dev-workspace/run b/dev-workspace/run
--- a/dev-workspace/run
+++ b/dev-workspace/run
@@ -1,12 +1,51 @@
 #!/usr/bin/env bash
 
-# If not in the `dev-workspace` directory, change to it
-if [[ ! $(pwd) =~ .*dev-workspace$ ]]; then
-  cd dev-workspace
+show_help() {
+    echo "Usage: $0 [command]"
+    echo ""
+    echo "If you are outside the dev-workspace terminal, this script will start"
+    echo "the dev-workspace environment and execute your command inside it."
+    echo "If you are already inside the dev-workspace terminal, your command"
+    echo "will be executed directly within the current environment."
+    echo ""
+    echo "Available commands:"
+    echo "  -h, --help: Show this help message"
+    echo "  <command>: Run a command in the dev-workspace"
+}
+
+check_env_file() {
+    if [[ ! -f .env ]]; then
+        echo "Error: .env file not found in the root directory. Please run 'cp .env.example .env' to create it."
+        exit 1
+    fi
+}
+
+set_env_file() {
+    set -a
+    source .env
+    set +a
+}
+
+run_in_dev_workspace() {
+    if [ -z "$INSIDE_DEV_WORKSPACE" ]; then
+        echo "Initializing dev-workspace environment. Please wait..."
+
+        # If not in the `dev-workspace` directory, change to it
+        if [[ ! $(pwd) =~ .*dev-workspace$ ]]; then
+            cd dev-workspace
+        fi
+
+        bash ./scripts/terminal-service-run.sh "$@"
+    else
+        $@
+    fi
+}
+
+if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+    show_help
+    exit 0
 fi
 
-set -a
-source ../.env
-set +a
-
-bash ./scripts/terminal-service-run.sh "$@"
+check_env_file
+set_env_file
+run_in_dev_workspace "$@"
