Release v1.4.0

diff --git a/dev-workspace/stop b/dev-workspace/stop
--- a/dev-workspace/stop
+++ b/dev-workspace/stop
@@ -5,8 +5,13 @@ if [[ ! $(pwd) =~ .*dev-workspace$ ]]; then
   cd dev-workspace
 fi
 
+if [[ ! -f ../.env ]]; then
+  echo "Error: .env file not found in the root directory. Please run 'cp .env.example .env' to create it."
+  exit 1
+fi
+
 set -a
-source ./.env
+source ../.env
 set +a
 
-$BIN_PATH/exec stop "$@"
+sh ./scripts/terminal-service-stop.sh
